version: '3.9'

services:

  xenforo_src:
    image: alpine
    command: ["uptime"]
    volumes:
      - .:/var/www/html

  php-fpm:
    image: xfrocks/xenforo:php-fpm
    volumes_from:
      - xenforo_src
    
  nginx:
    image: xfrocks/xenforo:nginx
    environment:
      - VIRTUAL_HOST=localhost
      - NGINX_FAST_CGI_PASS=php-fpm:9000
    expose:
      - "80"
    links:
      - php-fpm
    volumes_from:
      - xenforo_src

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro